export const homeBanner = [
  {
    imgUrl:"https://i.postimg.cc/V6Rrdsk1/banner-1.jpg",
    bannerSubtitle:"Trending Accessories",
    bannerTitle:"Modern Sunglasses",
    price:"15",
  },
  {
    imgUrl:"https://i.postimg.cc/RFXhvPgZ/banner-2.jpg",
    bannerSubtitle:"Sale Offer",
    bannerTitle:"New Fashion Summer Sale",
    price:"19",
  },
  {
    imgUrl:"https://i.postimg.cc/MTKZ37z2/banner-3.jpg",
    bannerSubtitle:"Trending Item",
    bannerTitle:"Women's latest fashion sale",
    price:"43",
  }
] 

export const perfumeBanner = [
  {
    imgUrl:"https://images.pexels.com/photos/965992/pexels-photo-965992.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    bannerSubtitle:"Sale Offer",
    bannerTitle:"New Midnight Musk",
    price:"19",
  },
  {
    imgUrl:"https://images.pexels.com/photos/3910071/pexels-photo-3910071.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    bannerSubtitle:"Trending Fragrance",
    bannerTitle:"Narciso",
    price:"2999",
  },
  {
    imgUrl:"https://static.vecteezy.com/system/resources/thumbnails/050/679/598/small_2x/elegant-perfume-bottles-displayed-artistically-among-branches-and-yellow-accents-in-a-dark-misty-setting-photo.jpg",
    bannerSubtitle:"New Fragrance",
    bannerTitle:"Atkinsons",
    price:"120",
  }
]

export const jewelleryBanner = [
  {
    imgUrl:"https://images.pexels.com/photos/3634366/pexels-photo-3634366.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    bannerSubtitle:"Sale Offer",
    bannerTitle:"Bracelets",
    price:"19",
  },
  {
    imgUrl:"https://images.pexels.com/photos/1191531/pexels-photo-1191531.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    bannerSubtitle:"Trending Items",
    bannerTitle:"Hand Band",
    price:"9",
  },
  {
    imgUrl:"https://static.vecteezy.com/system/resources/thumbnails/054/418/829/small/elegant-gold-hoop-earrings-with-sparkling-gemstones-on-a-textured-textile-background-free-photo.jpeg",
    bannerSubtitle:"New Earings",
    bannerTitle:"Atkinsons",
    price:"120",
  }
]

export const menBanner = [
  {
    imgUrl:"https://images.pexels.com/photos/7413893/pexels-photo-7413893.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    bannerSubtitle:"Sale Offer",
    bannerTitle:"Leather Jackets",
    price:"19",
  },
  {
    imgUrl:"https://static.vecteezy.com/system/resources/thumbnails/024/229/341/small/sustainable-clothing-items-including-eco-friendly-jeans-and-tops-generative-ai-photo.jpg",
    bannerSubtitle:"Trending Items",
    bannerTitle:"Chinos Pants",
    price:"9",
  },
  {
    imgUrl:"https://static.vecteezy.com/system/resources/thumbnails/052/947/179/small/a-collection-of-colorful-shirts-hanging-on-black-hangers-in-a-store-photo.jpeg",
    bannerSubtitle:"Sale Offer",
    bannerTitle:"Hot Hoddies",
    price:"120",
  }
]

export const womenBanner = [
  {
    imgUrl:"https://images.pexels.com/photos/7413893/pexels-photo-7413893.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    bannerSubtitle:"Sale Offer",
    bannerTitle:"Floral Summer ",
    price:"1499",
  },
  {
    imgUrl:"https://images.pexels.com/photos/29547631/pexels-photo-29547631/free-photo-of-casual-style-with-striped-shirt-on-marble-steps.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    bannerSubtitle:"Trending Items",
    bannerTitle:"Ankel Boots",
    price:"49",
  },
  {
    imgUrl:"https://images.pexels.com/photos/9543412/pexels-photo-9543412.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    bannerSubtitle:"Sale Offer",
    bannerTitle:"Skinny Jeans",
    price:"120",
  }
]

export const Deal = [
  {
    id: "13",
    title: "SHAMPOO, CONDITIONER & FACEWASH PACKS",
    disc: "Old Spice includes a variety of products designed for men's grooming needs, such as deodorants and antiperspirants, body washes, shaving creams, aftershaves, and hair and beard care",
    price: 150.00,
    lastPrice: 200.00,
    imgUrl: "https://i.postimg.cc/wjGDnM81/shampoo.jpg",
    star: "★ ★ ★ ★ ★ "
  },
  {
    id: "14",
    title: "ROSE GOLD DIAMOND EARRINGS",
    disc: "It's a stylish piece of jewelry that combines the warm tones of rose gold with the brilliance of diamonds. Enjoy a a luxurious and elegant accessory, perfect for enhancing any outfit while adding a touch of sophistication",
    price: 1990.00,
    lastPrice: 2000.00,
    imgUrl: "https://i.postimg.cc/6qd3mpCv/jewellery-1.jpg",
    star: "★ ★ ★ ★ ★ "
  },
  {
    id: "15",
    title: "Mens Winter Leathers Jackets",
    disc: "Old Spice includes a variety of products designed for men's grooming needs, such as deodorants and antiperspirants, body washes, shaving creams, aftershaves, and hair and beard care",
    price: 150.00,
    lastPrice: 200.00,
    imgUrl: "https://i.postimg.cc/T36WRKJp/jacket-2.jpg",
    star: "★ ★ ★ ★ ★ "
  },
]

export const product = [
  {
    id: "1",
    title: "Jacket",
    disc: "Mens Winter Leathers Jackets",
    price: 48.00,
    lastPrice: 75.00,
    imgUrl: "https://i.postimg.cc/jdybNKWJ/jacket-3.jpg",
    imgUrlH: "https://i.postimg.cc/pr9cj4HT/jacket-4.jpg",
    star: "★ ★ ★ ★ ★ ",
    isOnSale:true
  },
  {
    id: "2",
    title: "Shirt",
    disc: "Pure Garment Dyed Cotton Shirt",
    price: 45.00,
    lastPrice: 56.00,
    imgUrl: "https://i.postimg.cc/02w43fPg/shirt-1.jpg",
    imgUrlH: "https://i.postimg.cc/dVbq6JMK/shirt-2.jpg",
    star: "★ ★ ★ ★ ★ "
  },
  {
    id: "3",
    title: "Jacket",
    disc: "  MEN Yarn Fleece Full-Zip Jacket",
    price: 58.00,
    lastPrice: 65.00,
    imgUrl: "https://i.postimg.cc/DZ3QSqRG/jacket-5.jpg",
    imgUrlH: "https://i.postimg.cc/RFnYQp6s/jacket-6.jpg",
    star: "★ ★ ★ ★ ★ "
  },
  {
    id: "4",
    title: "Skirt",
    disc: "   Black Floral Wrap Midi Skirt",
    price: 25.00,
    lastPrice: 35.00,
    imgUrl: "https://i.postimg.cc/DzgH6wF8/clothes-3.jpg",
    imgUrlH: "https://i.postimg.cc/g01SJySv/clothes-4.jpg",
    star: "★ ★ ★ ★ ★ ",
    isOnSale:true

  },
  {
    id: "5",
    title: "Casuel",
    disc: "Casual Men's Brown shoes",
    price: 99.00,
    lastPrice: 105.0,
    imgUrl: "https://i.postimg.cc/0yCHGD6R/shoe-2.jpg",
    imgUrlH: "https://i.postimg.cc/TY29THdz/shoe-2-1.jpg",
    star: "★ ★ ★ ★ ★ "
  },
  {
    id: "6",
    title: "Watches",
    disc: "Pocket Watch Leather Pouch",
    price: 150.0,
    lastPrice: 170.0,
    imgUrl: "https://i.postimg.cc/jq84QT45/watch-3.jpg",
    imgUrlH: "https://i.postimg.cc/tRk3vt32/watch-4.jpg",
    star: "★ ★ ★ ★ ★ ",
    isOnSale:true
  },
  {
    id: "7",
    title: "Watches",
    disc: "Smart watche Vital Plus",
    price: 100.0,
    lastPrice: 120.0,
    imgUrl: "https://i.postimg.cc/rsk1gH6g/watch-1.jpg",
    imgUrlH: "https://i.postimg.cc/hjgmpfhk/watch-2.jpg",
    star: "★ ★ ★ ★ ★ "
  },
  {
    id: "8",
    title: "Party Wear",
    disc: "Womens Party Wear Shoes",
    price: 25.00,
    lastPrice: 35.00,
    imgUrl: "https://i.postimg.cc/qRPjQYmZ/party-wear-1.jpg",
    imgUrlH: "https://i.postimg.cc/FKhF6cgV/party-wear-2.jpg",
    star: "★ ★ ★ ★ ★ "
  },
  {
    id: "9",
    title: "Jacket",
    disc: "Mens Winter Leathers Jackets",
    price: 32.00,
    lastPrice: 45.00,
    imgUrl: "https://i.postimg.cc/9fnSKNRh/jacket-1.jpg",
    imgUrlH: "https://i.postimg.cc/T36WRKJp/jacket-2.jpg",
    star: "★ ★ ★ ★ ★ ",
    isOnSale:true

  },
  {
    id: "10",
    title: "Sports",
    disc: "Trekking & Running Shoes - black",
    price: 48.00,
    lastPrice: 65.00,
    imgUrl: "https://i.postimg.cc/DfjFzzbv/sports-2.jpg",
    imgUrlH: "https://i.postimg.cc/BbFX338T/sports-4.jpg",
    star: "★ ★ ★ ★ ★ "
  },
  {
    id: "11",
    title: "Formal",
    disc: "Men's Leather Formal Wear shoes",
    price: 78.00,
    lastPrice: 85.00,
    imgUrl: "https://i.postimg.cc/JnMtkwB5/shoe-1.jpg",
    imgUrlH: "https://i.postimg.cc/BnLwGwNq/shoe-1-1.jpg",
    star: "★ ★ ★ ★ ★ ",
    isOnSale:true

  },
  {
    id: "12",
    title: "Shorts",
    disc: "Better Basics French Terry Sweatshorts",
    price: 78.00,
    lastPrice: 85.00,
    imgUrl: "https://i.postimg.cc/7Lmt7tMz/shorts-1.jpg",
    imgUrlH: "https://i.postimg.cc/cLBTZywG/shorts-2.jpg",
    star: "★ ★ ★ ★ ★ "
  },
]

export const newArrival = [
  {
    id: "16",
    title: "Clothes",
    disc: "Relaxed Short full sleeve t-shirt",
    price: 150.0,
    lastPrice: 200.00,
    imgUrl: "https://i.postimg.cc/fyLNm09z/clothes-1.jpg",
    star: "★ ★ ★ ★ ★ "
  },
  {
    id: "17",
    title: "Clothes",
    disc: "Girls pink Embro design top",
    price: 1990.00,
    lastPrice: 2000.00,
    imgUrl: "https://i.postimg.cc/T3mXVxpD/clothes-2.jpg",
    star: "★ ★ ★ ★ ★ "
  },
  {
    id: "18",
    title: "Clothes",
    disc: "Black Floral Wrap Midi Skirt",
    price: 150.00,
    lastPrice: 200.00,
    imgUrl: "https://i.postimg.cc/DzgH6wF8/clothes-3.jpg",
    star: "★ ★ ★ ★ ★ "
  },
  {
    id: "19",
    title: "Mens Fashions",
    disc: "Pure Garment Dyed Cotton Shirt",
    price: 150.00,
    lastPrice: 200.00,
    imgUrl: "https://i.postimg.cc/02w43fPg/shirt-1.jpg",
    star: "★ ★ ★ ★ ★ "
  },
]

export const trending = [
  {
    id: "20",
    title: "Clothes",
    disc: "Relaxed Short full sleeve t-shirt",
    price: 150.00,
    lastPrice: 200.00,
    imgUrl: "https://i.postimg.cc/DZ3QSqRG/jacket-5.jpg",
    star: "★ ★ ★ ★ ★ "
  },
  {
    id: "21",
    title: "Winter Wear",
    disc: "Men Yarn Fleece Full-zip Jacket",
    price: 1990.00,
    lastPrice: 2000.00,
    imgUrl: "https://i.postimg.cc/9fnSKNRh/jacket-1.jpg",
    star: "★ ★ ★ ★ ★ "
  },
  {
    id: "22",
    title: "Jackets",
    disc: "Mens Winter Leathers Jackets",
    price: 50.00,
    lastPrice: 200.00,
    imgUrl: "https://i.postimg.cc/jdybNKWJ/jacket-3.jpg",
    star: "★ ★ ★ ★ ★ "
  },
  {
    id: "23",
    title: "Shorts",
    disc: "Better Basics French Terry Sweatshorts",
    price: 150.00,
    lastPrice: 200.00,
    imgUrl: "https://i.postimg.cc/7Lmt7tMz/shorts-1.jpg",
    star: "★ ★ ★ ★ ★ "
  },
]

export const bestSeller = [
  {
    id: "24",
    title: "Baby fabric shoes",
    price: 5.00,
    lastPrice: 4.00,
    imgUrl: "https://i.postimg.cc/kGZn4GL2/1.jpg",
    star: "★ ★ ★ ★ ★ "
  },
  {
    id: "25",
    title: "Men's hoodies t-shirt",
    price: 1990.00,
    lastPrice: 2000.00,
    imgUrl: "https://i.postimg.cc/fySG8Kgb/2.jpg",
    star: "★ ★ ★ ★ ★ "
  },
  {
    id: "26",
    title: "Girl T-Shirt",
    price: 150.00,
    lastPrice: 200.00,
    imgUrl: "https://i.postimg.cc/14xL2qLr/3.jpg",
    star: "★ ★ ★ ★ ★ "
  }, {
    id: "27",
    title: "Woolen Hat for Men",
    price: 150.00,
    lastPrice: 200.00,
    imgUrl: "https://i.postimg.cc/y6wxsrKv/4.jpg",
    star: "★ ★ ★ ★ ★ "
  },
]

export const blogCard = [
  {
    title: "Fashions",
    imgUrl: "https://i.postimg.cc/2886v00v/blog-1.jpg",
    disc: "Clothes Retail KPIs 2023 Guide for Clothes Executives",
    name: "Mr Admin",
    date: "Apr 06, 2024",
  },
  {
    title: "Clothes",
    imgUrl: "https://i.postimg.cc/cJWPgbmG/blog-2.jpg",
    disc: "Curbside fashion Trends: How to Win the Pickup Battle",
    name: "Mr Robin",
    date: "Jan 18, 2024",
  }, {
    title: "Shoes",
    imgUrl: "https://i.postimg.cc/BQkj0xCK/blog-3.jpg",
    disc: "EBT vendors: Claim Your Share of SNAP Online Revenue",
    name: "Mr Selsa",
    date: "Feb 23, 2023",
  }, {
    title: "Electronics",
    imgUrl: "https://i.postimg.cc/43Jskdjc/blog-4.jpg",
    disc: "Curbside fashion Trends: How to Win the Pickup Battle",
    name: "Mr Pawar",
    date: "Feb 02, 2023",
  },
]

export const hotOffer = [
  {
    id: "66",
    title: "Wireless Bluetooth Earbuds",
    disc: "Experience the freedom of wireless music with these high-quality Bluetooth earbuds. Perfect for workouts, commutes, and daily use.",
    price: 120.0,
    lastPrice: 150.0,
    imgUrl: "https://static.vecteezy.com/system/resources/thumbnails/051/199/431/small/earbuds-mockup-resting-clean-surface-with-soft-lighting-ideal-for-showcasing-tech-products-photo.jpg",
    star: "★ ★ ★ ★ ☆",
    sold: "12",
    avai: "50",
    day: "15",
    hour: "20",
    min: "35",
    sec: "50",
  },
  {
    id: "67",
    title: "ROSE GOLD DIAMOND EARRINGS",
    disc: "It's a stylish piece of jewelry that combines the warm tones of rose gold with the brilliance of diamonds. Enjoy a a luxurious and elegant accessory, perfect for enhancing any outfit while adding a touch of sophistication",
    price: 1990.0,
    lastPrice: 2000.0,
    imgUrl: "https://static.vecteezy.com/system/resources/thumbnails/054/416/509/small/elegant-gold-and-diamond-earrings-displayed-on-a-textured-surface-under-soft-golden-light-free-photo.jpeg",
    star: "★ ★ ★ ★ ★",
    sold: "17",
    avai: "30",
    day: "32",
    hour: "51",
    min: "56",
    sec: "34",
  },
  {
    id: "68",
    title: "Mens Winter Leathers Jackets",
    disc: "Stay warm and stylish this winter with these high-quality leather jackets designed for durability and comfort.",
    price: 150.0,
    lastPrice: 200.0,
    imgUrl: "https://static.vecteezy.com/system/resources/thumbnails/048/987/532/small/handsome-fashion-model-in-a-leather-jacket-set-against-a-graffiti-wall-in-a-male-dress-urban-lifestyle-fashion-portrait-with-a-boldlifestyle-males-portrait-fashion-male-background-free-photo.jpg",
    star: "★ ★ ★ ★ ★",
    sold: "15",
    avai: "26",
    day: "6",
    hour: "31",
    min: "46",
    sec: "4",
  },
  {
    id: "69",
    title: "Gaming Mechanical Keyboard",
    disc: "Enhance your gaming experience with this RGB-backlit mechanical keyboard featuring responsive keys and customizable lighting.",
    price: 80.0,
    lastPrice: 100.0,
    imgUrl: "https://static.vecteezy.com/system/resources/thumbnails/019/625/163/small/above-top-view-student-gamer-workspace-concept-gaming-gear-mouse-keyboard-joystick-headset-on-white-background-with-copy-space-and-nutrition-for-kid-elementary-set-up-free-photo.jpg",
    star: "★ ★ ★ ★ ☆",
    sold: "22",
    avai: "40",
    day: "12",
    hour: "45",
    min: "20",
    sec: "15",
  },
  {
    id: "70",
    title: "Fitness Smartwatch",
    disc: "Track your fitness journey with this advanced smartwatch featuring heart rate monitoring, step tracking, and more.",
    price: 250.0,
    lastPrice: 300.0,
    imgUrl: "https://static.vecteezy.com/system/resources/thumbnails/022/853/441/small/artificial-intelligence-smart-watch-generative-ai-photo.JPG",
    star: "★ ★ ★ ★ ★",
    sold: "35",
    avai: "20",
    day: "18",
    hour: "10",
    min: "5",
    sec: "30",
  },
  {
    id: "71",
    title: "4K Ultra HD Action Camera",
    disc: "Capture your adventures in stunning 4K resolution with this compact and durable action camera.",
    price: 180.0,
    lastPrice: 220.0,
    imgUrl: "https://static.vecteezy.com/system/resources/thumbnails/047/379/949/small/view-of-a-digital-black-camera-on-white-background-photo.jpg",
    star: "★ ★ ★ ★ ☆",
    sold: "10",
    avai: "15",
    day: "10",
    hour: "5",
    min: "50",
    sec: "20",
  },
  {
    id: "72",
    title: "Luxury Leather Handbag",
    disc: "Elevate your style with this premium leather handbag, designed for versatility and elegance.",
    price: 320.0,
    lastPrice: 400.0,
    imgUrl: "https://static.vecteezy.com/system/resources/thumbnails/049/726/658/small/up-close-shot-of-a-structured-tophandle-bag-featuring-a-statementmaking-chain-link-s-and-luxe-diamondshaped-hardware-photo.jpg",
    star: "★ ★ ★ ★ ★",
    sold: "8",
    avai: "25",
    day: "25",
    hour: "15",
    min: "45",
    sec: "10",
  },
];


export const perfume = [
  {
    id: "31",
    title: "Aqua Intense",
    disc: "A fresh aquatic fragrance perfect for daily wear.",
    price: 2999,
    lastPrice: 3499,
    imgUrl: "https://images.unsplash.com/photo-1605619082574-e92eee603b95?q=80&w=1762&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    imgUrlH: "https://images.pexels.com/photos/12456259/pexels-photo-12456259.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    star: "★ ★ ★ ★ ★ ",
    isOnSale:true
  },
  {
    id: "32",
    title: "Urban Spice",
    disc: "A spicy and woody scent for urban adventurers.",
    price: 3199,
    lastPrice: 3799,
    imgUrl: "https://images.pexels.com/photos/932577/pexels-photo-932577.jpeg?auto=compress&cs=tinysrgb&w=600",
    imgUrlH: "https://images.pexels.com/photos/965989/pexels-photo-965989.jpeg?auto=compress&cs=tinysrgb&w=600",
    star: "★ ★ ★ ★ ★ ",
  },
  {
    id: "33",
    title: "Citrus Burst",
    disc: "A zesty citrus fragrance to energize your senses.",
    price: 2499,
    lastPrice: 2999,
    imgUrl: "https://images.pexels.com/photos/6694194/pexels-photo-6694194.jpeg?auto=compress&cs=tinysrgb&w=600",
    imgUrlH: "https://images.pexels.com/photos/4612154/pexels-photo-4612154.jpeg?auto=compress&cs=tinysrgb&w=600",
    star: "★ ★ ★ ★ ★ ",
    isOnSale:true
  },
  
  {
    id: "34",
    title: "Midnight Musk",
    disc: "An alluring musk scent for evening occasions.",
    price: 3499,
    lastPrice: 3999,
    imgUrl: "https://images.pexels.com/photos/27467869/pexels-photo-27467869/free-photo-of-cosmetics-on-bed.jpeg?auto=compress&cs=tinysrgb&w=600",
    imgUrlH: "https://images.pexels.com/photos/27783031/pexels-photo-27783031/free-photo-of-beach-bag-with-sunscreen-and-perfume-bottles-near-straw-hat.jpeg?auto=compress&cs=tinysrgb&w=600",
    star: "★ ★ ★ ★ ★ ",
  },
  {
    id: "35",
    title: "Ocean Breeze",
    disc: "A breezy, marine-inspired fragrance.",
    price: 2799,
    lastPrice: 3299,
    imgUrl: "https://images.pexels.com/photos/1961791/pexels-photo-1961791.jpeg?auto=compress&cs=tinysrgb&w=600",
    imgUrlH: "https://images.pexels.com/photos/21904493/pexels-photo-21904493/free-photo-of-woman-in-satin-blouse-holding-bottle-of-expensive-perfume.jpeg?auto=compress&cs=tinysrgb&w=600",
    star: "★ ★ ★ ★ ★ ",
  },
  {
    id: "36",
    title: "Woody Legend",
    disc: "A deep, woody scent for the bold and confident.",
    price: 3599,
    lastPrice: 4199,
    imgUrl: "https://images.pexels.com/photos/8450399/pexels-photo-8450399.jpeg?auto=compress&cs=tinysrgb&w=600",
    imgUrlH: "https://images.pexels.com/photos/8450345/pexels-photo-8450345.jpeg?auto=compress&cs=tinysrgb&w=600",
    star: "★ ★ ★ ★ ★ ",
    isOnSale:true
  },
  {
    id: "37",
    title: "Fresh Cedar",
    disc: "A refreshing cedar fragrance for a crisp aura.",
    price: 2699,
    lastPrice: 3199,
    imgUrl: "https://images.pexels.com/photos/1666405/pexels-photo-1666405.jpeg?auto=compress&cs=tinysrgb&w=600",
    imgUrlH: "https://images.pexels.com/photos/10536629/pexels-photo-10536629.jpeg?auto=compress&cs=tinysrgb&w=600",
    star: "★ ★ ★ ★ ★ ",
  },
  {
    id: "38",
    title: "Amber Touch",
    disc: "A warm amber scent with a touch of sophistication.",
    price: 3299,
    lastPrice: 3899,
    imgUrl: "https://images.pexels.com/photos/27489058/pexels-photo-27489058/free-photo-of-bottles-of-perfume.jpeg?auto=compress&cs=tinysrgb&w=600",
    imgUrlH: "https://images.pexels.com/photos/9944432/pexels-photo-9944432.jpeg?auto=compress&cs=tinysrgb&w=600",
    star: "★ ★ ★ ★ ★ ",
  },
]

export const bestPerfume = [
  {
    id: "31",
    title: "Aqua Intense",
    disc: "A fresh aquatic fragrance perfect for daily wear.",
    price: 2999,
    lastPrice: 3499,
    imgUrl: "https://images.unsplash.com/photo-1605619082574-e92eee603b95?q=80&w=1762&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    imgUrlH: "https://images.pexels.com/photos/12456259/pexels-photo-12456259.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    star: "★ ★ ★ ★ ★ ",
  },
  {
    id: "34",
    title: "Midnight Musk",
    disc: "An alluring musk scent for evening occasions.",
    price: 3499,
    lastPrice: 3999,
    imgUrl: "https://images.pexels.com/photos/27467869/pexels-photo-27467869/free-photo-of-cosmetics-on-bed.jpeg?auto=compress&cs=tinysrgb&w=600",
    imgUrlH: "https://images.pexels.com/photos/27783031/pexels-photo-27783031/free-photo-of-beach-bag-with-sunscreen-and-perfume-bottles-near-straw-hat.jpeg?auto=compress&cs=tinysrgb&w=600",
    star: "★ ★ ★ ★ ★ ",
  },
  {
    id: "35",
    title: "Ocean Breeze",
    disc: "A breezy, marine-inspired fragrance.",
    price: 2799,
    lastPrice: 3299,
    imgUrl: "https://images.pexels.com/photos/1961791/pexels-photo-1961791.jpeg?auto=compress&cs=tinysrgb&w=600",
    imgUrlH: "https://images.pexels.com/photos/21904493/pexels-photo-21904493/free-photo-of-woman-in-satin-blouse-holding-bottle-of-expensive-perfume.jpeg?auto=compress&cs=tinysrgb&w=600",
    star: "★ ★ ★ ★ ★ ",
  },
  {
    id: "36",
    title: "Woody Legend",
    disc: "A deep, woody scent for the bold and confident.",
    price: 3599,
    lastPrice: 4199,
    imgUrl: "https://images.pexels.com/photos/8450399/pexels-photo-8450399.jpeg?auto=compress&cs=tinysrgb&w=600",
    imgUrlH: "https://images.pexels.com/photos/8450345/pexels-photo-8450345.jpeg?auto=compress&cs=tinysrgb&w=600",
    star: "★ ★ ★ ★ ★ ",
  },
]


export const jewelry = [
  {
    id: "39",
    title: "Elegant Necklace",
    disc: "A stunning necklace with a modern design.",
    price: 4999,
    lastPrice: 5999,
    imgUrl: "https://images.pexels.com/photos/691046/pexels-photo-691046.jpeg?auto=compress&cs=tinysrgb&w=600",
    imgUrlH: "https://images.pexels.com/photos/860009/pexels-photo-860009.jpeg?auto=compress&cs=tinysrgb&w=600",
    star: "★ ★ ★ ★ ★",
  },
  {
    id: "40",
    title: "Diamond Earrings",
    disc: "Elegant earrings featuring sparkling diamonds.",
    price: 6999,
    lastPrice: 7999,
    imgUrl: "https://images.pexels.com/photos/177332/pexels-photo-177332.jpeg?auto=compress&cs=tinysrgb&w=600",
    imgUrlH: "https://images.pexels.com/photos/298852/pexels-photo-298852.jpeg?auto=compress&cs=tinysrgb&w=600",
    isOnSale:true,
    star: "★ ★ ★ ★ ★",
  },
  {
    id: "41",
    title: "Gold Bracelet",
    disc: "A classic gold bracelet for all occasions.",
    price: 8999,
    lastPrice: 9999,
    imgUrl: "https://images.pexels.com/photos/27173093/pexels-photo-27173093/free-photo-of-person-hand-over-dough.jpeg?auto=compress&cs=tinysrgb&w=600",
    imgUrlH: "https://images.pexels.com/photos/6019185/pexels-photo-6019185.jpeg?auto=compress&cs=tinysrgb&w=600",
    star: "★ ★ ★ ★ ★",
  },
  {
    id: "42",
    title: "Luxury Watch",
    disc: "A stylish watch with a sleek design.",
    price: 11999,
    lastPrice: 12999,
    imgUrl: "https://images.pexels.com/photos/190819/pexels-photo-190819.jpeg?auto=compress&cs=tinysrgb&w=600",
    imgUrlH: "https://images.pexels.com/photos/2113994/pexels-photo-2113994.jpeg?auto=compress&cs=tinysrgb&w=600",
    star: "★ ★ ★ ★ ★",
  },
  {
    id: "43",
    title: "Silver Necklace",
    disc: "A simple yet elegant silver necklace.",
    price: 3499,
    lastPrice: 3999,
    imgUrl: "https://media.istockphoto.com/id/163122066/photo/round-diamonds-necklace.jpg?b=1&s=612x612&w=0&k=20&c=rTSIudGVfUwJzD9sPnpYoO5KzjSZ2AZ67bHJTSa3kAI=",
    imgUrlH: "https://media.istockphoto.com/id/1355399132/photo/model-showing-her-beautiful-necklace-with-diamond-pendant.jpg?b=1&s=612x612&w=0&k=20&c=2HToo9ZI_6Fs20S0HRroACbBIYwgnbeWXb9Ype61FZw=",
    star: "★ ★ ★ ★ ★",
    isOnSale:true
  },
  {
    id: "44",
    title: "Rose Gold Ring",
    disc: "A beautiful rose gold ring with intricate designs.",
    price: 12999,
    lastPrice: 13999,
    imgUrl: "https://images.pexels.com/photos/248077/pexels-photo-248077.jpeg?auto=compress&cs=tinysrgb&w=600",
    imgUrlH: "https://images.pexels.com/photos/1457801/pexels-photo-1457801.jpeg?auto=compress&cs=tinysrgb&w=600",
    star: "★ ★ ★ ★ ★",
  },
  {
    id: "45",
    title: "Pearl Earrings",
    disc: "Elegant pearl earrings for a sophisticated look.",
    price: 5999,
    lastPrice: 6999,
    imgUrl: "https://images.pexels.com/photos/458766/pexels-photo-458766.jpeg?auto=compress&cs=tinysrgb&w=600",
    imgUrlH: "https://images.pexels.com/photos/886603/pexels-photo-886603.jpeg?auto=compress&cs=tinysrgb&w=600",
    star: "★ ★ ★ ★ ★",
    isOnSale:true
  },
  {
    id: "46",
    title: "Gold Anklet",
    disc: "A delicate gold anklet for a chic appearance.",
    price: 4499,
    lastPrice: 4999,
    imgUrl: "https://images.pexels.com/photos/2944422/pexels-photo-2944422.jpeg?auto=compress&cs=tinysrgb&w=600",
    imgUrlH: "https://images.pexels.com/photos/9185032/pexels-photo-9185032.jpeg?auto=compress&cs=tinysrgb&w=600",
    star: "★ ★ ★ ★ ★",
  },
];


export const bestJewelry = [
  {
    id: "42",
    title: "Luxury Watch",
    disc: "A stylish watch with a sleek design.",
    price: 11999,
    lastPrice: 12999,
    imgUrl: "https://images.pexels.com/photos/190819/pexels-photo-190819.jpeg?auto=compress&cs=tinysrgb&w=600",
    imgUrlH: "https://images.pexels.com/photos/2113994/pexels-photo-2113994.jpeg?auto=compress&cs=tinysrgb&w=600",
    star: "★ ★ ★ ★ ★",
  },{
    id: "39",
    title: "Elegant Necklace",
    disc: "A stunning necklace with a modern design.",
    price: 4999,
    lastPrice: 5999,
    imgUrl: "https://images.pexels.com/photos/691046/pexels-photo-691046.jpeg?auto=compress&cs=tinysrgb&w=600",
    imgUrlH: "https://images.pexels.com/photos/860009/pexels-photo-860009.jpeg?auto=compress&cs=tinysrgb&w=600",
    star: "★ ★ ★ ★ ★",
  },{
    id: "45",
    title: "Pearl Earrings",
    disc: "Elegant pearl earrings for a sophisticated look.",
    price: 5999,
    lastPrice: 6999,
    imgUrl: "https://images.pexels.com/photos/458766/pexels-photo-458766.jpeg?auto=compress&cs=tinysrgb&w=600",
    imgUrlH: "https://images.pexels.com/photos/886603/pexels-photo-886603.jpeg?auto=compress&cs=tinysrgb&w=600",
    star: "★ ★ ★ ★ ★",
  },{
    id: "44",
    title: "Rose Gold Ring",
    disc: "A beautiful rose gold ring with intricate designs.",
    price: 12999,
    lastPrice: 13999,
    imgUrl: "https://images.pexels.com/photos/248077/pexels-photo-248077.jpeg?auto=compress&cs=tinysrgb&w=600",
    imgUrlH: "https://images.pexels.com/photos/1457801/pexels-photo-1457801.jpeg?auto=compress&cs=tinysrgb&w=600",
    star: "★ ★ ★ ★ ★",
  },
]



export const Mens = [
  {
    id: "49",
    title: "Classic White Shirt",
    disc: "A timeless piece, perfect for any occasion.",
    price: 1299,
    lastPrice: 1599,
    imgUrl: "https://images.pexels.com/photos/1304647/pexels-photo-1304647.jpeg?auto=compress&cs=tinysrgb&w=600",
    imgUrlH: "https://images.pexels.com/photos/4066288/pexels-photo-4066288.jpeg?auto=compress&cs=tinysrgb&w=600",
    star: "★ ★ ☆ ☆ ☆ ",
  },
  {
    id: "50",
    title: "Blue Denim Jeans",
    disc: "Stylish and comfortable for everyday wear.",
    price: 1599,
    lastPrice: 1999,
    imgUrl: "https://images.pexels.com/photos/1598507/pexels-photo-1598507.jpeg?auto=compress&cs=tinysrgb&w=600",
    imgUrlH: "https://images.pexels.com/photos/1082526/pexels-photo-1082526.jpeg?auto=compress&cs=tinysrgb&w=600",
    star: "★ ★ ★ ☆ ☆ ",
  },
  {
    id: "51",
    title: "Grey Hoodie",
    disc: "A cozy hoodie for casual outings and workouts.",
    price: 1699,
    lastPrice: 2099,
    imgUrl: "https://images.pexels.com/photos/5319493/pexels-photo-5319493.jpeg?auto=compress&cs=tinysrgb&w=600",
    imgUrlH: "https://images.pexels.com/photos/7706413/pexels-photo-7706413.jpeg?auto=compress&cs=tinysrgb&w=600",
    star: "★ ★ ★ ★ ★ ",
    isOnSale:true
  },
  {
    id: "52",
    title: "Leather Jacket",
    disc: "A sleek leather jacket for a sophisticated look.",
    price: 2999,
    lastPrice: 3499,
    imgUrl: "https://images.pexels.com/photos/7748383/pexels-photo-7748383.jpeg?auto=compress&cs=tinysrgb&w=600",
    imgUrlH: "https://images.pexels.com/photos/20232810/pexels-photo-20232810/free-photo-of-young-man-in-a-brown-leather-jacket-standing-by-the-river.jpeg?auto=compress&cs=tinysrgb&w=600",
    star: "★ ★ ★ ★ ★ ",
  },
  {
    id: "53",
    title: "Casual Sneakers",
    disc: "Stylish sneakers for everyday comfort.",
    price: 1999,
    lastPrice: 2399,
    imgUrl: "https://images.pexels.com/photos/1478442/pexels-photo-1478442.jpeg?auto=compress&cs=tinysrgb&w=600",
    imgUrlH: "https://images.pexels.com/photos/267202/pexels-photo-267202.jpeg?auto=compress&cs=tinysrgb&w=600",
    star: "★ ★ ☆ ☆ ☆ ",
    isOnSale:true
  },
  {
    id: "54",
    title: "Chinos Pants",
    disc: "Versatile chinos for a smart casual look.",
    price: 1799,
    lastPrice: 2199,
    imgUrl: "https://images.pexels.com/photos/10074957/pexels-photo-10074957.jpeg?auto=compress&cs=tinysrgb&w=600",
    imgUrlH: "https://images.pexels.com/photos/9929648/pexels-photo-9929648.jpeg?auto=compress&cs=tinysrgb&w=600",
    star: "★ ★ ★ ☆ ☆ ",
  },
  {
    id: "55",
    title: "T-shirt Pack",
    disc: "A set of comfortable, everyday T-shirts.",
    price: 999,
    lastPrice: 1299,
    imgUrl: "https://images.pexels.com/photos/30005111/pexels-photo-30005111/free-photo-of-stylish-young-man-posing-with-jacket-outdoors.jpeg?auto=compress&cs=tinysrgb&w=600",
    imgUrlH: "https://images.pexels.com/photos/30005113/pexels-photo-30005113/free-photo-of-stylish-man-posing-in-minimalist-urban-setting.jpeg?auto=compress&cs=tinysrgb&w=600",
    star: "★ ★ ★ ☆ ☆ ",
    isOnSale:true
  },
  {
    id: "56",
    title: "Blazer Suit",
    disc: "Elegant blazer suit for formal occasions.",
    price: 3999,
    lastPrice: 4599,
    imgUrl: "https://images.pexels.com/photos/30042490/pexels-photo-30042490/free-photo-of-black-and-white-portrait-of-man-in-suit-and-sunglasses.jpeg?auto=compress&cs=tinysrgb&w=600",
    imgUrlH: "https://images.pexels.com/photos/30042493/pexels-photo-30042493/free-photo-of-dramatic-portrait-of-man-in-vintage-style.jpeg?auto=compress&cs=tinysrgb&w=600",
    star: "★ ★ ★ ★ ☆ ",
  },
];


export const bestMens = [
  {
    id: "50",
    title: "Blue Denim Jeans",
    disc: "Stylish and comfortable for everyday wear.",
    price: 1599,
    lastPrice: 1999,
    imgUrl: "https://images.pexels.com/photos/1598507/pexels-photo-1598507.jpeg?auto=compress&cs=tinysrgb&w=600",
    imgUrlH: "https://images.pexels.com/photos/1082526/pexels-photo-1082526.jpeg?auto=compress&cs=tinysrgb&w=600",
    star: "★ ★ ★ ☆ ☆  ",
  },
  {
    id: "56",
    title: "Blazer Suit",
    disc: "Elegant blazer suit for formal occasions.",
    price: 3999,
    lastPrice: 4599,
    imgUrl: "https://images.pexels.com/photos/30042490/pexels-photo-30042490/free-photo-of-black-and-white-portrait-of-man-in-suit-and-sunglasses.jpeg?auto=compress&cs=tinysrgb&w=600",
    imgUrlH: "https://images.pexels.com/photos/30042493/pexels-photo-30042493/free-photo-of-dramatic-portrait-of-man-in-vintage-style.jpeg?auto=compress&cs=tinysrgb&w=600",
    star: "★ ★ ★ ★ ☆ ",
  },
  {
    id: "49",
    title: "Classic White Shirt",
    disc: "A timeless piece, perfect for any occasion.",
    price: 1299,
    lastPrice: 1599,
    imgUrl: "https://images.pexels.com/photos/1304647/pexels-photo-1304647.jpeg?auto=compress&cs=tinysrgb&w=600",
    imgUrlH: "https://images.pexels.com/photos/4066288/pexels-photo-4066288.jpeg?auto=compress&cs=tinysrgb&w=600",
    star: "★ ★ ☆ ☆ ☆",
  },
  {
    id: "54",
    title: "Chinos Pants",
    disc: "Versatile chinos for a smart casual look.",
    price: 1799,
    lastPrice: 2199,
    imgUrl: "https://images.pexels.com/photos/10074957/pexels-photo-10074957.jpeg?auto=compress&cs=tinysrgb&w=600",
    imgUrlH: "https://images.pexels.com/photos/9929648/pexels-photo-9929648.jpeg?auto=compress&cs=tinysrgb&w=600",
    star: "★ ★ ★ ☆ ☆ ",
  },
 
]

export const Women = [
  {
    id: "57",
    title: "Floral Summer Dress",
    disc: "A breezy, vibrant dress perfect for warm days.",
    price: 1499,
    lastPrice: 1999,
    imgUrl: "https://images.pexels.com/photos/247204/pexels-photo-247204.jpeg?auto=compress&cs=tinysrgb&w=600",
    imgUrlH: "https://images.pexels.com/photos/1082526/pexels-photo-1082526.jpeg?auto=compress&cs=tinysrgb&w=600",
    star: "★ ★ ★ ☆ ☆",
    isOnSale:true
  },
  {
    id: "58",
    title: "Casual White Blouse",
    disc: "A versatile blouse for both work and leisure.",
    price: 999,
    lastPrice: 1299,
    imgUrl: "https://images.pexels.com/photos/1126998/pexels-photo-1126998.jpeg?auto=compress&cs=tinysrgb&w=600",
    imgUrlH: "https://images.pexels.com/photos/1138746/pexels-photo-1138746.jpeg?auto=compress&cs=tinysrgb&w=600",
    star: "★ ★  ☆ ☆ ☆",
  },
  {
    id: "59",
    title: "High-Waist Skinny Jeans",
    disc: "Comfortable and stylish jeans for everyday wear.",
    price: 1299,
    lastPrice: 1699,
    imgUrl: "https://images.pexels.com/photos/532220/pexels-photo-532220.jpeg?auto=compress&cs=tinysrgb&w=600",
    imgUrlH: "https://images.pexels.com/photos/631148/pexels-photo-631148.jpeg?auto=compress&cs=tinysrgb&w=600",
    star: "★ ★ ★ ☆ ☆",
  },
  {
    id: "60",
    title: "Pleated Midi Skirt",
    disc: "A chic skirt for a sophisticated look.",
    price: 1799,
    lastPrice: 2199,
    imgUrl: "https://images.pexels.com/photos/3775563/pexels-photo-3775563.jpeg?auto=compress&cs=tinysrgb&w=600",
    imgUrlH: "https://images.pexels.com/photos/2951124/pexels-photo-2951124.jpeg?auto=compress&cs=tinysrgb&w=600",
    star: "★ ★ ★ ★ ★",
    isOnSale:true
  },
  {
    id: "611",
    title: "Leather Jacket",
    disc: "A sleek leather jacket to elevate your style.",
    price: 2999,
    lastPrice: 3499,
    imgUrl: "https://images.pexels.com/photos/7748383/pexels-photo-7748383.jpeg?auto=compress&cs=tinysrgb&w=600",
    imgUrlH: "https://images.pexels.com/photos/20232810/pexels-photo-20232810/free-photo-of-young-man-in-a-brown-leather-jacket-standing-by-the-river.jpeg?auto=compress&cs=tinysrgb&w=600",
    star: "★ ★ ★ ★ ☆",
  },
  {
    id: "61",
    title: "Knitted Cardigan",
    disc: "Stay warm and stylish with this cozy cardigan.",
    price: 1999,
    lastPrice: 2499,
    imgUrl: "https://images.pexels.com/photos/1148986/pexels-photo-1148986.jpeg?auto=compress&cs=tinysrgb&w=600",
    imgUrlH: "https://images.pexels.com/photos/1222273/pexels-photo-1222273.jpeg?auto=compress&cs=tinysrgb&w=600",
    star: "★ ★ ★ ☆ ☆",
    isOnSale:true
  },
  {
    id: "62",
    title: "Evening Gown",
    disc: "A glamorous gown for formal events.",
    price: 4999,
    lastPrice: 5499,
    imgUrl: "https://images.pexels.com/photos/4668275/pexels-photo-4668275.jpeg?auto=compress&cs=tinysrgb&w=600",
    imgUrlH: "https://images.pexels.com/photos/3823487/pexels-photo-3823487.jpeg?auto=compress&cs=tinysrgb&w=600",
    star: "★ ★ ☆ ☆ ☆",
  },
  {
    id: "63",
    title: "Activewear Set",
    disc: "Comfortable and stylish for workouts.",
    price: 1299,
    lastPrice: 1699,
    imgUrl: "https://images.pexels.com/photos/1148986/pexels-photo-1148986.jpeg?auto=compress&cs=tinysrgb&w=600",
    imgUrlH: "https://images.pexels.com/photos/1222273/pexels-photo-1222273.jpeg?auto=compress&cs=tinysrgb&w=600",
    star: "★ ★ ★ ☆ ☆",
  },
  {
    id: "64",
    title: "Ankle Boots",
    disc: "Trendy boots for a modern touch.",
    price: 2499,
    lastPrice: 2999,
    imgUrl: "https://images.pexels.com/photos/179909/pexels-photo-179909.jpeg?auto=compress&cs=tinysrgb&w=600",
    imgUrlH: "https://images.pexels.com/photos/459064/pexels-photo-459064.jpeg?auto=compress&cs=tinysrgb&w=600",
    star: "★ ★ ★ ★ ☆ ☆",
    isOnSale:true
  },
  {
    id: "65",
    title: "Handcrafted Earrings",
    disc: "Elegant earrings for a graceful touch.",
    price: 499,
    lastPrice: 799,
    imgUrl: "https://images.pexels.com/photos/1242528/pexels-photo-1242528.jpeg?auto=compress&cs=tinysrgb&w=600",
    imgUrlH: "https://images.pexels.com/photos/1828473/pexels-photo-1828473.jpeg?auto=compress&cs=tinysrgb&w=600",
    star: "★ ★ ★ ★ ☆",
  },
];

export const bestWomen = [
  {
    id: "61",
    title: "Knitted Cardigan",
    disc: "Stay warm and stylish with this cozy cardigan.",
    price: 1999,
    lastPrice: 2499,
    imgUrl: "https://images.pexels.com/photos/1148986/pexels-photo-1148986.jpeg?auto=compress&cs=tinysrgb&w=600",
    imgUrlH: "https://images.pexels.com/photos/1222273/pexels-photo-1222273.jpeg?auto=compress&cs=tinysrgb&w=600",
    star: "★ ★  ☆ ☆",
  },
  {
    id: "57",
    title: "Floral Summer Dress",
    disc: "A breezy, vibrant dress perfect for warm days.",
    price: 1499,
    lastPrice: 1999,
    imgUrl: "https://images.pexels.com/photos/247204/pexels-photo-247204.jpeg?auto=compress&cs=tinysrgb&w=600",
    imgUrlH: "https://images.pexels.com/photos/1082526/pexels-photo-1082526.jpeg?auto=compress&cs=tinysrgb&w=600",
    star: "★ ★ ☆ ☆ ☆",
  },  {
    id: "64",
    title: "Ankle Boots",
    disc: "Trendy boots for a modern touch.",
    price: 2499,
    lastPrice: 2999,
    imgUrl: "https://images.pexels.com/photos/179909/pexels-photo-179909.jpeg?auto=compress&cs=tinysrgb&w=600",
    imgUrlH: "https://images.pexels.com/photos/459064/pexels-photo-459064.jpeg?auto=compress&cs=tinysrgb&w=600",
    star: "★ ★ ★ ★ ☆",
  }, {
    id: "59",
    title: "High-Waist Skinny Jeans",
    disc: "Comfortable and stylish jeans for everyday wear.",
    price: 1299,
    lastPrice: 1699,
    imgUrl: "https://images.pexels.com/photos/532220/pexels-photo-532220.jpeg?auto=compress&cs=tinysrgb&w=600",
    imgUrlH: "https://images.pexels.com/photos/631148/pexels-photo-631148.jpeg?auto=compress&cs=tinysrgb&w=600",
    star: "★ ★ ★ ☆ ☆",
  },
]

export const Clothe = [
  {
    id: "66",
    title: "Casual Cotton Shirt",
    disc: "A lightweight and comfortable cotton shirt, ideal for daily wear.",
    price: 1299,
    lastPrice: 1599,
    imgUrl: "https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&w=600",
    imgUrlH: "https://images.pexels.com/photos/935985/pexels-photo-935985.jpeg?auto=compress&cs=tinysrgb&w=600",
    star: "★ ★ ★ ★ ☆",
  },
  {
    id: "67",
    title: "Denim Jeans",
    disc: "Classic blue denim jeans for a timeless style.",
    price: 1599,
    lastPrice: 1999,
    imgUrl: "https://images.pexels.com/photos/874996/pexels-photo-874996.jpeg?auto=compress&cs=tinysrgb&w=600",
    imgUrlH: "https://images.pexels.com/photos/1238947/pexels-photo-1238947.jpeg?auto=compress&cs=tinysrgb&w=600",
    star: "★ ★ ★ ☆ ☆",
    isOnSale: true,
  },
  {
    id: "68",
    title: "Fleece Jacket",
    disc: "A cozy fleece jacket for chilly weather.",
    price: 2499,
    lastPrice: 2999,
    imgUrl: "https://images.pexels.com/photos/1371164/pexels-photo-1371164.jpeg?auto=compress&cs=tinysrgb&w=600",
    imgUrlH: "https://images.pexels.com/photos/574964/pexels-photo-574964.jpeg?auto=compress&cs=tinysrgb&w=600",
    star: "★ ★ ★ ★ ☆",
  },
  {
    id: "69",
    title: "Summer Maxi Dress",
    disc: "A flowy maxi dress for hot summer days.",
    price: 1999,
    lastPrice: 2599,
    imgUrl: "https://images.pexels.com/photos/3657429/pexels-photo-3657429.jpeg?auto=compress&cs=tinysrgb&w=600",
    imgUrlH: "https://images.pexels.com/photos/3786094/pexels-photo-3786094.jpeg?auto=compress&cs=tinysrgb&w=600",
    star: "★ ★ ★ ★ ★",
    isOnSale: true,
  },
  {
    id: "70",
    title: "Classic Polo T-Shirt",
    disc: "A stylish polo t-shirt for casual outings.",
    price: 1099,
    lastPrice: 1499,
    imgUrl: "https://images.pexels.com/photos/3756168/pexels-photo-3756168.jpeg?auto=compress&cs=tinysrgb&w=600",
    imgUrlH: "https://images.pexels.com/photos/4021971/pexels-photo-4021971.jpeg?auto=compress&cs=tinysrgb&w=600",
    star: "★ ★ ★ ☆ ☆",
  },
  {
    id: "71",
    title: "Knitted Pullover",
    disc: "Warm knitted pullover for cozy winter evenings.",
    price: 1799,
    lastPrice: 2299,
    imgUrl: "https://images.pexels.com/photos/594701/pexels-photo-594701.jpeg?auto=compress&cs=tinysrgb&w=600",
    imgUrlH: "https://images.pexels.com/photos/935759/pexels-photo-935759.jpeg?auto=compress&cs=tinysrgb&w=600",
    star: "★ ★ ★ ★ ☆",
  },
  {
    id: "72",
    title: "Formal Trousers",
    disc: "Elegant formal trousers for office wear.",
    price: 1899,
    lastPrice: 2399,
    imgUrl: "https://images.pexels.com/photos/4171637/pexels-photo-4171637.jpeg?auto=compress&cs=tinysrgb&w=600",
    imgUrlH: "https://images.pexels.com/photos/5180659/pexels-photo-5180659.jpeg?auto=compress&cs=tinysrgb&w=600",
    star: "★ ★ ★ ★ ☆",
  },
  {
    id: "73",
    title: "Pleated Skirt",
    disc: "A stylish pleated skirt to elevate your look.",
    price: 1499,
    lastPrice: 1999,
    imgUrl: "https://images.pexels.com/photos/209657/pexels-photo-209657.jpeg?auto=compress&cs=tinysrgb&w=600",
    imgUrlH: "https://images.pexels.com/photos/158709/pexels-photo-158709.jpeg?auto=compress&cs=tinysrgb&w=600",
    star: "★ ★ ★ ☆ ☆",
  },
  {
    id: "74",
    title: "Sports Tracksuit",
    disc: "Durable and lightweight tracksuit for workouts.",
    price: 2199,
    lastPrice: 2799,
    imgUrl: "https://images.pexels.com/photos/2611870/pexels-photo-2611870.jpeg?auto=compress&cs=tinysrgb&w=600",
    imgUrlH: "https://images.pexels.com/photos/2608025/pexels-photo-2608025.jpeg?auto=compress&cs=tinysrgb&w=600",
    star: "★ ★ ★ ★ ☆",
  },
  {
    id: "75",
    title: "Woolen Scarf",
    disc: "Soft woolen scarf to keep you warm.",
    price: 799,
    lastPrice: 1199,
    imgUrl: "https://images.pexels.com/photos/428338/pexels-photo-428338.jpeg?auto=compress&cs=tinysrgb&w=600",
    imgUrlH: "https://images.pexels.com/photos/933374/pexels-photo-933374.jpeg?auto=compress&cs=tinysrgb&w=600",
    star: "★ ★ ★ ★ ★",
  },
];

export const Footwears = [
  {
    id: "76",
    title: "Running Shoes",
    disc: "Lightweight and durable running shoes for all terrains.",
    price: 2499,
    lastPrice: 2999,
    imgUrl: "https://static.vecteezy.com/system/resources/thumbnails/035/423/753/small/close-up-of-woman-s-legs-on-start-before-jogging-photo.jpg",
    imgUrlH: "https://static.vecteezy.com/system/resources/thumbnails/026/431/785/small/running-shoes-in-the-city-sports-and-healthy-lifestyle-concept-ai-generative-photo.jpg",
    star: "★ ★ ★ ★ ☆",
    isOnSale: true,
  },
  {
    id: "77",
    title: "Casual Sneakers",
    disc: "Trendy sneakers for daily comfort and style.",
    price: 1999,
    lastPrice: 2499,
    imgUrl: "https://static.vecteezy.com/system/resources/thumbnails/018/964/840/small/green-youth-sneakers-hanging-on-a-nail-photo.jpg",
    imgUrlH: "https://images.pexels.com/photos/1598505/pexels-photo-1598505.jpeg?auto=compress&cs=tinysrgb&w=600",
    star: "★ ★ ★ ★ ★",
  },
  {
    id: "78",
    title: "Formal Leather Shoes",
    disc: "Classic leather shoes for a sharp formal look.",
    price: 2999,
    lastPrice: 3499,
    imgUrl: "https://static.vecteezy.com/system/resources/thumbnails/053/847/648/small/a-pair-of-black-shoes-free-photo.jpg",
    imgUrlH: "https://static.vecteezy.com/system/resources/thumbnails/009/666/336/small/black-men-s-shoes-in-bright-sunshine-free-photo.jpg",
    star: "★ ★ ★ ★ ☆",
  },
  {
    id: "79",
    title: "Flip-Flops",
    disc: "Comfortable and stylish flip-flops for casual outings.",
    price: 499,
    lastPrice: 799,
    imgUrl: "https://static.vecteezy.com/system/resources/thumbnails/006/572/677/small/flip-flops-on-beach-sand-with-focus-on-foreground-photo.jpg",
    imgUrlH: "https://static.vecteezy.com/system/resources/thumbnails/002/193/401/small/flip-flop-isolated-on-white-free-photo.jpg",
    star: "★ ★ ☆ ☆ ☆",
    isOnSale: true,
  },
  {
    id: "80",
    title: "Hiking Boots",
    disc: "Sturdy boots designed for adventurous hiking trips.",
    price: 3999,
    lastPrice: 4499,
    imgUrl: "https://static.vecteezy.com/system/resources/thumbnails/053/894/857/small/brown-hiking-boots-resting-on-rocky-path-with-blue-backpack-nearby-in-a-lush-green-landscape-photo.jpg",
    imgUrlH: "https://static.vecteezy.com/system/resources/thumbnails/036/749/658/small/ai-generated-hiking-boots-on-a-rocky-mountain-trail-during-golden-hour-photo.jpg",
    star: "★ ★ ★ ★ ★",
  },
  {
    id: "81",
    title: "Ankle Boots",
    disc: "Stylish ankle boots for a chic look.",
    price: 3499,
    lastPrice: 3999,
    imgUrl: "https://static.vecteezy.com/system/resources/thumbnails/013/621/370/small/female-winter-leather-shoes-free-photo.jpg",
    imgUrlH: "https://static.vecteezy.com/system/resources/thumbnails/013/619/990/small/female-winter-leather-shoes-free-photo.jpg",
    star: "★ ★ ★ ☆ ☆",
  },
  {
    id: "82",
    title: "Loafers",
    disc: "Comfortable loafers for both formal and casual wear.",
    price: 2599,
    lastPrice: 2999,
    imgUrl: "https://static.vecteezy.com/system/resources/thumbnails/001/995/868/small/leather-loafers-on-a-dock-free-photo.JPG",
    imgUrlH: "https://static.vecteezy.com/system/resources/thumbnails/046/086/508/small/a-pair-of-highquality-timeless-leather-loafers-displayed-on-a-shelf-photo.jpg",
    star: "★ ★ ★ ★ ☆",
  },
  {
    id: "83",
    title: "Slippers",
    disc: "Soft and cozy slippers for indoor comfort.",
    price: 799,
    lastPrice: 999,
    imgUrl: "https://static.vecteezy.com/system/resources/thumbnails/013/667/373/small/brand-new-beautiful-slippers-photo.jpg",
    imgUrlH: "https://static.vecteezy.com/system/resources/thumbnails/009/207/338/small/slipper-on-cement-floor-free-photo.jpg",
    star: "★ ★ ★ ☆ ☆",
  },
  {
    id: "84",
    title: "Sandals",
    disc: "Comfortable sandals for summer days.",
    price: 1399,
    lastPrice: 1799,
    imgUrl: "https://static.vecteezy.com/system/resources/thumbnails/036/422/086/small/black-cowhide-sandals-leather-sandals-for-men-photo.JPG",
    imgUrlH: "https://static.vecteezy.com/system/resources/thumbnails/021/577/835/small/sandals-in-the-sand-photo.jpg",
    star: "★ ★ ★ ☆ ☆",
  },
  {
    id: "85",
    title: "Heels",
    disc: "Elegant high heels for parties and formal occasions.",
    price: 2799,
    lastPrice: 3299,
    imgUrl: "https://static.vecteezy.com/system/resources/thumbnails/023/329/301/small/woman-in-black-heels-sitting-at-home-generative-ai-photo.jpg",
    imgUrlH: "https://static.vecteezy.com/system/resources/thumbnails/008/999/700/small/woman-legs-with-high-heels-photo.jpg",
    star: "★ ★ ★ ★ ★",
    isOnSale: true,
  },
];

export const Cosmetic = [
  {
    id: "86",
    title: "Matte Lipstick",
    disc: "Long-lasting matte lipstick available in various shades.",
    price: 499,
    lastPrice: 699,
    imgUrl: "https://static.vecteezy.com/system/resources/thumbnails/037/386/167/small/red-lipstick-with-water-drops-on-a-dark-background-photo.jpg",
    imgUrlH: "https://static.vecteezy.com/system/resources/thumbnails/053/741/819/small/a-red-lipstick-is-on-a-pink-cloth-the-lipstick-is-shiny-and-has-a-glittery-texture-photo.jpg",
    star: "★ ★ ★ ★ ☆",
    isOnSale: true,
  },
  {
    id: "87",
    title: "Liquid Foundation",
    disc: "Lightweight foundation for a smooth and even finish.",
    price: 999,
    lastPrice: 1299,
    imgUrl: "https://static.vecteezy.com/system/resources/thumbnails/028/699/995/small/liquid-makeup-foundation-bottle-generate-ai-photo.jpg",
    imgUrlH: "https://static.vecteezy.com/system/resources/thumbnails/028/206/985/small/liquid-foundation-splash-fluid-cosmetic-cream-profesionalgrapy-ai-generated-photo.jpg",
    star: "★ ★ ★ ★ ☆",
  },
  {
    id: "88",
    title: "Eyeshadow Palette",
    disc: "A palette with 12 vibrant colors for bold eye makeup.",
    price: 1299,
    lastPrice: 1599,
    imgUrl: "https://static.vecteezy.com/system/resources/thumbnails/032/844/078/small/multi-colored-eyeshadow-palette-vibrant-colors-in-a-shiny-container-generated-by-ai-free-photo.jpg",
    imgUrlH: "https://static.vecteezy.com/system/resources/thumbnails/053/729/007/small/a-well-used-eyeshadow-palette-displays-vibrant-colors-photo.jpeg",
    star: "★ ★ ★ ★ ★",
    isOnSale: true,
  },
  {
    id: "89",
    title: "Mascara",
    disc: "Waterproof mascara for voluminous lashes.",
    price: 699,
    lastPrice: 899,
    imgUrl: "https://static.vecteezy.com/system/resources/thumbnails/014/348/050/small/black-wand-and-smudged-mascara-on-white-background-free-photo.jpg",
    imgUrlH: "https://static.vecteezy.com/system/resources/thumbnails/025/490/910/small/sharp-metallic-mascara-a-beauty-tool-for-glamorous-eyes-generated-by-ai-free-photo.jpg",
    star: "★ ★ ★ ★ ☆",
  },
  {
    id: "90",
    title: "Blush",
    disc: "Powder blush for a natural and radiant glow.",
    price: 599,
    lastPrice: 799,
    imgUrl: "https://static.vecteezy.com/system/resources/thumbnails/016/627/570/small/crushed-eyeshadow-face-powder-and-makeup-brushes-isolated-on-white-background-makeup-composition-with-copy-space-free-space-for-text-photo.jpg",
    imgUrlH: "https://static.vecteezy.com/system/resources/thumbnails/053/642/913/small/round-block-refill-blush-with-a-relief-pattern-of-pink-tone-and-a-scattering-of-dry-blush-on-a-white-background-texture-a-sample-of-blush-top-view-photo.jpg",
    star: "★ ★ ★ ☆ ☆",
  },
  {
    id: "91",
    title: "Makeup Brushes Set",
    disc: "Set of 10 high-quality brushes for flawless makeup application.",
    price: 1499,
    lastPrice: 1999,
    imgUrl: "https://static.vecteezy.com/system/resources/thumbnails/036/006/794/small/ai-generated-ergonomic-makeup-brush-generate-ai-photo.jpg",
    imgUrlH: "https://static.vecteezy.com/system/resources/thumbnails/014/887/398/small/makeup-brushes-beauty-set-copy-space-photo.JPG",
    star: "★ ★ ★ ★ ☆",
  },
  {
    id: "92",
    title: "Compact Powder",
    disc: "Lightweight compact powder for a matte finish.",
    price: 799,
    lastPrice: 999,
    imgUrl: "https://static.vecteezy.com/system/resources/thumbnails/049/573/294/small/compact-powder-cases-with-mirror-finish-set-against-a-backdrop-of-softly-blurred-orchids-professional-shot-highlighting-the-sleek-design-and-reflective-quality-of-the-powder-cases-photo.jpeg",
    imgUrlH: "https://static.vecteezy.com/system/resources/thumbnails/051/208/189/small/compact-powder-makeup-palette-sitting-on-mirrored-surface-photo.jpg",
    star: "★ ★ ★ ☆ ☆",
  },
  {
    id: "93",
    title: "Highlighter Stick",
    disc: "Creamy highlighter stick for a luminous glow.",
    price: 999,
    lastPrice: 1299,
    imgUrl: "https://static.vecteezy.com/system/resources/thumbnails/049/573/148/small/radiant-bronzer-sticks-with-a-golden-sheen-with-a-blurred-background-of-orchids-professional-shot-emphasizing-the-warm-tones-and-luxurious-finish-of-the-bronzer-sticks-photo.jpeg",
    imgUrlH: "https://static.vecteezy.com/system/resources/thumbnails/054/052/839/small/collection-of-smudged-lipsticks-isolated-on-white-photo.jpg",
    star: "★ ★ ★ ★ ☆",
  },
  {
    id: "94",
    title: "Nail Polish Set",
    disc: "Set of 6 vibrant nail polishes for every mood.",
    price: 899,
    lastPrice: 1199,
    imgUrl: "https://static.vecteezy.com/system/resources/thumbnails/049/573/150/small/glittering-nail-polish-bottles-in-metallic-shades-placed-in-front-of-a-backdrop-of-softly-blurred-daisies-professional-shot-highlighting-the-sparkling-finish-and-variety-of-the-nail-polishes-photo.jpeg",
    imgUrlH: "https://static.vecteezy.com/system/resources/thumbnails/049/573/342/small/elegant-nail-polish-bottles-in-bold-colors-with-a-blurred-garden-of-marigolds-behind-professional-shot-highlighting-the-vibrant-and-striking-shades-of-the-nail-polish-photo.jpeg",
    star: "★ ★ ★ ☆ ☆",
  },
  {
    id: "95",
    title: "Lip Balm",
    disc: "Hydrating lip balm for soft and smooth lips.",
    price: 299,
    lastPrice: 499,
    imgUrl: "https://static.vecteezy.com/system/resources/thumbnails/034/781/583/small/hygienic-moisturizing-lip-balm-in-a-tube-on-a-orange-background-photo.jpg",
    imgUrlH: "https://static.vecteezy.com/system/resources/thumbnails/012/747/583/small/woman-with-beauty-face-applying-lip-balm-photo.jpg",
    star: "★ ★ ★ ★ ☆",
  },
];

export const Glass = [
  {
    id: "96",
    title: "Aviator Sunglasses",
    disc: "Classic aviator sunglasses for a timeless look.",
    price: 1599,
    lastPrice: 1999,
    imgUrl: "https://static.vecteezy.com/system/resources/thumbnails/027/117/087/small/man-or-woman-aviator-style-fashionable-attractive-elegance-sun-glasses-studio-shot-dark-indoor-background-ai-generated-photo.jpg",
    imgUrlH: "https://static.vecteezy.com/system/resources/thumbnails/027/118/952/small/fancy-trendy-modest-red-color-dark-lens-man-or-woman-fashionable-attractive-aviator-sun-glasses-at-the-studio-shot-ai-generated-photo.jpg",
    star: "★ ★ ★ ★ ☆",
    isOnSale: true,
  },
  {
    id: "97",
    title: "Round Sunglasses",
    disc: "Trendy round sunglasses for a vintage style.",
    price: 1299,
    lastPrice: 1699,
    imgUrl: "https://static.vecteezy.com/system/resources/thumbnails/047/160/018/small/close-up-of-round-blue-sunglasses-on-white-background-free-photo.jpg",
    imgUrlH: "https://static.vecteezy.com/system/resources/thumbnails/013/587/796/small/stylish-black-sunglasses-with-round-glasses-lies-on-a-blanket-made-of-soft-and-fluffy-light-blue-fleece-fabric-fashionable-background-picture-in-female-colors-photo.JPG",
    star: "★ ★ ★ ★ ☆",
  },
  {
    id: "98",
    title: "Cat-Eye Sunglasses",
    disc: "Stylish cat-eye sunglasses for a chic look.",
    price: 1799,
    lastPrice: 2299,
    imgUrl: "https://static.vecteezy.com/system/resources/thumbnails/046/369/853/small/sunglasses-are-on-the-bed-close-up-photo.jpg",
    imgUrlH: "https://static.vecteezy.com/system/resources/thumbnails/054/612/009/small/cat-eye-sunglasses-on-white-background-photo.jpg",
    star: "★ ★ ★ ★ ★",
  },
  {
    id: "99",
    title: "Polarized Sports Glasses",
    disc: "Durable sports glasses with polarized lenses for outdoor activities.",
    price: 2499,
    lastPrice: 2999,
    imgUrl: "https://static.vecteezy.com/system/resources/thumbnails/040/858/992/small/bicycle-helmet-and-bike-glasses-on-the-street-rock-with-blurred-background-free-photo.jpg",
    imgUrlH: "https://static.vecteezy.com/system/resources/thumbnails/044/419/820/small/active-female-cyclist-in-helmet-and-sunglasses-poses-confidently-in-sportswear-photo.jpeg",
    star: "★ ★ ★ ★ ☆",
    isOnSale: true,
  },
  {
    id: "100",
    title: "Blue Light Glasses",
    disc: "Protect your eyes from screen glare with blue light glasses.",
    price: 999,
    lastPrice: 1299,
    imgUrl: "https://static.vecteezy.com/system/resources/thumbnails/051/262/099/small/best-selling-blue-light-blocking-glasses-photo.jpeg",
    imgUrlH: "https://static.vecteezy.com/system/resources/thumbnails/047/512/511/small/best-selling-blue-light-blocking-glasses-photo.jpeg",
    star: "★ ★ ★ ★ ☆",
  },
  {
    id: "101",
    title: "Wayfarer Sunglasses",
    disc: "Iconic wayfarer sunglasses for a bold look.",
    price: 1999,
    lastPrice: 2499,
    imgUrl: "https://static.vecteezy.com/system/resources/thumbnails/051/199/614/small/stylish-sunglasses-mockup-resting-a-sandy-beach-with-bright-sunlight-perfect-for-showcasing-summerthemed-accessory-branding-and-outdoor-vibes-photo.jpg",
    imgUrlH: "https://static.vecteezy.com/system/resources/thumbnails/051/067/950/small/a-pair-of-sunglasses-on-a-table-in-front-of-a-couch-free-photo.jpeg",
    star: "★ ★ ★ ☆ ☆",
  },
  {
    id: "102",
    title: "Square Frame Glasses",
    disc: "Elegant square frames for a modern touch.",
    price: 1499,
    lastPrice: 1899,
    imgUrl: "https://static.vecteezy.com/system/resources/thumbnails/052/076/861/small/stack-of-colorful-books-on-white-background-open-book-stack-of-books-isolated-on-background-education-read-study-school-library-dictionary-photo.JPG",
    imgUrlH: "https://static.vecteezy.com/system/resources/thumbnails/040/152/192/small/stylish-eyeglasses-over-background-optical-store-glasses-selection-eye-test-vision-examination-at-optician-fashion-accessories-concept-top-view-flat-lay-photo.jpg",
    star: "★ ★ ★ ★ ☆",
  },
  {
    id: "103",
    title: "Oversized Sunglasses",
    disc: "Oversized sunglasses for a glamorous look.",
    price: 2299,
    lastPrice: 2799,
    imgUrl: "https://static.vecteezy.com/system/resources/thumbnails/001/926/924/small/sunglasses-on-tropical-beach-free-photo.JPG",
    imgUrlH: "https://static.vecteezy.com/system/resources/thumbnails/023/094/521/small/sunglasses-isolated-on-white-photo.jpg",
    star: "★ ★ ★ ★ ★",
    isOnSale: true,
  },
  {
    id: "104",
    title: "Transparent Frames",
    disc: "Minimalist transparent frame glasses for a sleek style.",
    price: 1199,
    lastPrice: 1499,
    imgUrl: "https://static.vecteezy.com/system/resources/thumbnails/008/740/686/small/point-of-view-looking-through-a-pair-of-sunglasses-photo.jpg",
    imgUrlH: "https://static.vecteezy.com/system/resources/thumbnails/048/156/970/small/clear-sunglasses-with-blue-lenses-on-white-background-photo.jpg",
    star: "★ ★ ★ ☆ ☆",
  },
  {
    id: "105",
    title: "Retro Glasses",
    disc: "Vintage retro-style glasses for a bold statement.",
    price: 1399,
    lastPrice: 1799,
    imgUrl: "https://static.vecteezy.com/system/resources/thumbnails/024/946/302/small/white-cat-in-retro-style-yellow-glasses-on-light-green-background-with-copy-space-ai-generated-photo.jpg",
    imgUrlH: "https://static.vecteezy.com/system/resources/thumbnails/019/582/574/small/carnival-mask-with-feathers-and-typical-elements-in-the-background-photo.jpg",
    star: "★ ★ ★ ★ ☆",
  },
];

export const Bag = [
  {
    id: "106",
    title: "Leather Tote Bag",
    disc: "Spacious and elegant leather tote for daily use.",
    price: 2999,
    lastPrice: 3499,
    imgUrl: "https://static.vecteezy.com/system/resources/thumbnails/053/522/777/small/black-leather-tote-bag-with-sunbeams-and-shadows-photo.jpeg",
    imgUrlH: "https://static.vecteezy.com/system/resources/thumbnails/053/522/758/small/black-leather-tote-bag-on-a-white-and-teal-surface-with-shadows-photo.jpeg",
    star: "★ ★ ★ ★ ☆",
    isOnSale: true,
  },
  {
    id: "107",
    title: "Canvas Backpack",
    disc: "Durable and stylish backpack for travel or school.",
    price: 2499,
    lastPrice: 2999,
    imgUrl: "https://static.vecteezy.com/system/resources/thumbnails/049/857/680/small/a-blue-and-brown-backpack-sits-on-a-wooden-table-the-backpack-is-made-of-leather-and-has-a-brown-strap-photo.jpg",
    imgUrlH: "https://static.vecteezy.com/system/resources/thumbnails/051/177/412/small/a-blue-backpack-sits-on-a-wooden-stool-in-a-room-with-a-lot-of-books-the-room-has-a-cozy-and-inviting-atmosphere-with-a-mix-of-wooden-furniture-and-bookshelves-photo.jpg",
    star: "★ ★ ★ ★ ★",
  },
  {
    id: "108",
    title: "Crossbody Bag",
    disc: "Compact crossbody bag for a casual outing.",
    price: 1999,
    lastPrice: 2499,
    imgUrl: "https://static.vecteezy.com/system/resources/thumbnails/024/578/870/small/black-leather-backpack-with-buckle-and-zipper-for-stylish-travel-generated-by-ai-free-photo.jpg",
    imgUrlH: "https://static.vecteezy.com/system/resources/thumbnails/025/492/060/small/a-modern-luggage-bag-waits-in-a-luxurious-entrance-hall-generated-by-ai-free-photo.jpg",
    star: "★ ★ ★ ★ ☆",
  },
  {
    id: "109",
    title: "Laptop Bag",
    disc: "Sleek and professional laptop bag with multiple compartments.",
    price: 3499,
    lastPrice: 3999,
    imgUrl: "https://static.vecteezy.com/system/resources/thumbnails/043/499/297/small/hand-putting-laptop-computer-notebook-from-bag-photo.jpg",
    imgUrlH: "https://static.vecteezy.com/system/resources/thumbnails/043/499/293/small/hand-taking-laptop-computer-from-notebook-bag-photo.jpg",
    star: "★ ★ ★ ★ ☆",
    isOnSale: true,
  },
  {
    id: "110",
    title: "Duffel Bag",
    disc: "Versatile duffel bag for gym or weekend trips.",
    price: 2999,
    lastPrice: 3499,
    imgUrl: "https://static.vecteezy.com/system/resources/thumbnails/049/218/669/small/a-blue-gym-bag-placed-on-a-bench-in-a-locker-room-photo.jpeg",
    imgUrlH: "https://static.vecteezy.com/system/resources/thumbnails/049/218/673/small/a-blue-gym-bag-placed-on-a-bench-in-a-locker-room-photo.jpeg",
    star: "★ ★ ★ ★ ★",
  },
  {
    id: "111",
    title: "Clutch Bag",
    disc: "Elegant clutch bag for evening events and parties.",
    price: 1499,
    lastPrice: 1999,
    imgUrl: "https://static.vecteezy.com/system/resources/thumbnails/050/632/157/small/handbag-isolated-on-white-background-free-photo.jpg",
    imgUrlH: "https://static.vecteezy.com/system/resources/thumbnails/033/082/282/small/green-women-s-coin-purse-ai-generated-photo.jpg",
    star: "★ ★ ★ ★ ☆",
  },
  {
    id: "112",
    title: "Hiking Backpack",
    disc: "Large hiking backpack with ample storage space.",
    price: 3999,
    lastPrice: 4599,
    imgUrl: "https://static.vecteezy.com/system/resources/thumbnails/026/295/106/small/hiking-equipment-in-the-mountains-photo.jpg",
    imgUrlH: "https://static.vecteezy.com/system/resources/thumbnails/040/152/477/small/ai-generated-hiking-backpack-in-mountains-brown-travel-bag-in-nature-with-copy-space-hike-adventure-tourism-concept-photo.jpg",
    star: "★ ★ ★ ★ ★",
  },
  {
    id: "113",
    title: "Mini Backpack",
    disc: "Cute mini backpack for casual outings.",
    price: 1299,
    lastPrice: 1799,
    imgUrl: "https://static.vecteezy.com/system/resources/thumbnails/051/739/241/small/a-blue-backpack-and-a-stack-of-books-on-a-blue-background-photo.jpg",
    imgUrlH: "https://static.vecteezy.com/system/resources/thumbnails/053/407/784/small/gray-backpack-rests-on-desk-near-chairs-sunlight-fills-airy-bright-space-photo.jpg",
    star: "★ ★ ★ ☆ ☆",
  },
  {
    id: "114",
    title: "Shoulder Bag",
    disc: "Stylish shoulder bag for everyday essentials.",
    price: 2499,
    lastPrice: 2999,
    imgUrl: "https://static.vecteezy.com/system/resources/thumbnails/029/858/317/small/of-minimalist-black-leather-female-bag-isolated-on-white-background-generative-ai-photo.jpg",
    imgUrlH: "https://static.vecteezy.com/system/resources/thumbnails/029/858/421/small/of-minimalist-black-leather-female-bag-isolated-on-white-background-generative-ai-photo.jpg",
    star: "★ ★ ★ ★ ☆",
  },
  {
    id: "115",
    title: "Travel Bag",
    disc: "Lightweight travel bag with multiple compartments.",
    price: 4499,
    lastPrice: 4999,
    imgUrl: "https://static.vecteezy.com/system/resources/thumbnails/023/459/198/small/blue-background-with-suitcase-illustration-ai-generative-free-photo.jpg",
    imgUrlH: "https://static.vecteezy.com/system/resources/thumbnails/022/336/946/small/orange-suitcase-isolated-illustration-ai-generative-free-photo.jpg",
    star: "★ ★ ★ ★ ☆",
    isOnSale: true,
  },
];


